version: '3.8'

networks:
  shared-network:
    name: shared-network
    external: true

volumes:
  prometheus-data:
  grafana-data:


services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - ./monitoring:/monitoring # Mount code vào container
    networks:
      - shared-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring:/monitoring # Mount code vào container
    networks:
      - shared-network
    depends_on:
      - prometheus

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - ./monitoring:/monitoring # Mount code vào container
    networks:
      - shared-network

  celery-exporter:
    image: danihodovic/celery-exporter
    command: --broker-url redis://redis:6379/0
    ports:
      - "9808:9808"
    volumes:
      - ./monitoring:/monitoring # Mount code vào container
    networks:
      - shared-network
