global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'crawlermanager-backend-redis-exporter'
    static_configs:
      - targets: ['crawlermanager-backend-redis-exporter:9121']

  - job_name: 'crawlermanager-backend-celery-exporter'
    static_configs:
      - targets: ['crawlermanager-backend-celery-exporter:9808']

  - job_name: 'fastapi-crawlermanager-backend'
    static_configs:
    - targets: ['crawlermanager-backend:5042'] 
