global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'celery-exporter'
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: 'fastapi-backend'
    static_configs:
    - targets: ['api-server:5042'] 
